website/articles/routes.py
from flask import Blueprint, render_template
from flask_login import current_user


articles = Blueprint('articles', __name__)

Articles = {
    1: {
        'article_subject': 'creativity',
        'article_title': 'Embracing Creativity: Unleash the Power of Imagination',
        'article_content': "In a world that thrives on innovation and originality, creativity stands as the driving force behind some of the most groundbreaking ideas and inventions. From art and literature to technology and science, creativity paves the way for progress and pushes the boundaries of human capability Creativity is not an elusive trait reserved for a chosen few; it resides within each of us, waiting to be unleashed. Often, people underestimate their creative potential, believing that creativity is a gift bestowed upon a select few. However, the truth is that creativity can be cultivated and nurtured like a skill.",
        'article_image': 'creativity.jpg',
        'article_author': 'Pedro Furquim'
    },
    2: {
        'article_subject': 'organization',
        'article_title': 'Harnessing the Art of Organization: From Chaos to Clarity',
        'article_content': "In the fast-paced world we live in, the ability to stay organized is a superpower. It's not merely about neat desks and color-coded calendars; organization is the key to unlocking your productivity and maintaining a sense of control over your life.",
        'article_image': 'organization.jpg',
        'article_author': 'Pedro Furquim'
    }
}

@articles.route('/article/<string:article_subject>')
def article(article_subject):
    return render_template('article.html', article_subject=article_subject, articles=Articles, user=current_user)

website/notes/routes.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from website.models import Note, User
from sqlalchemy import desc
from .. import db
import json

notes =  Blueprint('notes', __name__)

@notes.route('/<int:note_id>', methods=['GET', 'POST'])
@login_required
def note(note_id):
    user = User.query.get(current_user.id)
    note = Note.query.get_or_404(note_id)
    return render_template('note.html', note=note, user=current_user)

@notes.route('/edit-note', methods=['POST'])
def edit_note():
    user = User.query.get(current_user.id)
    note_id = request.form.get('noteId')
    note = Note.query.get_or_404(note_id)
    
    page = request.args.get('page', 1, type=int)
    per_page = 10  # Number of notes to display per page

    new_text = request.form.get('edit_note')

    notes = Note.query.filter_by(user_id=user.id).order_by(desc(Note.date)).paginate(page=page, per_page=per_page)    


    if note:
        note.text = new_text
        db.session.commit()
        flash('Note edited!', category='success')
        return render_template("home.html", notes=notes, user=current_user)
    else:
        return render_template("home.html", notes=notes, user=current_user)

@notes.route('/delete-note', methods=['POST'])
def delete_note():
    note_data = json.loads(request.data)
    note_id = note_data['noteId']
    note = Note.query.get(note_id)
    
    if note and note.user_id == current_user.id:
        db.session.delete(note)
        db.session.commit()
        flash('Note deleted!', category='success')
    
    return jsonify({})

website/users/routes.py
from sqlalchemy import or_
from .utils import send_reset_email, save_picture
from flask import Blueprint,render_template, request, flash, redirect, url_for
from .. import User
from werkzeug.security import generate_password_hash, check_password_hash
from .. import db
from flask_login import login_user, login_required, logout_user, current_user

users = Blueprint('users', __name__)

@users.route("/getTime", methods=['GET'])
def getTime():
    time = request.args.get('time')
    return time

@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter(or_(User.email == email, User.username == username)).first()

        if user:
            if user.email == email:
                flash('Email already exists.', category='error')
            if user.username == username:
                flash('Username already exists.', category='error')
        elif len(email) < 4: 
            flash('Email must be greater than 3 characters.', category='error')
        elif len(email) > 99:
            flash('Email must be shorter than 100 characters.', category='error')
        elif len(username) < 2:
            flash('Username must be greater than 1 character.', category='error')
        elif len(username) > 10:
            flash('Username must be shorter than 10 characters.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif len(password1) > 15:
            flash('Password must be shorter than 15 characters.', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('main.home'))

    return render_template("register.html", user=current_user)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        remember = request.form.get('remember-me')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=bool(remember))
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        picture = request.files.get('picture', '')
        

        if email:
            if User.query.filter(User.email == email).filter(User.id != current_user.id).first():
                flash('Email already taken.', category='error')
            elif email == current_user.email:
                flash('Email already set.', category='error')
            else:
                if len(email) < 4:
                    flash('Email must be greater than 3 characters.', category='error')
                elif len(email) > 99:
                    flash('Email must be shorter than 100 characters.', category='error')
                else:
                    current_user.email = email
                    db.session.commit()
                    flash('Email updated.', category='success')


        if username:
            if User.query.filter(User.username == username).filter(User.id != current_user.id).first():
                flash('Username already taken.', category='error')
            elif username == current_user.username:
                flash('Username already set.', category='error')
            else:
                if len(username) < 2:
                    flash('Username must be greater than 1 character.', category='error')
                elif len(username) > 10:
                    flash('Username must be shorter than 11 characters.', category='error')
                else:
                    current_user.username = username
                    db.session.commit()
                    flash('Username updated.', category='success')
  
        if picture:
            picture_file = save_picture(picture, current_user)
            current_user.image_file = picture_file
            db.session.commit()
            flash('Picture updated.', category='success')



        
        return redirect(url_for('users.profile'))

    img_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("profile.html", user=current_user, img_file = img_file)

@users.route('/request', methods=['GET', 'POST'])
def request_page():
    if request.method == 'POST':
        
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()

        if user is None:
            flash('If an account with this email address exists, a password reset message will be sent shortly.', category="sucess")

        #Send Email to user
        send_reset_email(user) 
        flash('If an account with this email address exists, a password reset message will be sent shortly.', category="sucess")
        return redirect(url_for('users.login'))
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    return render_template('request.html', user=current_user)

@users.route('/reset-<token>', methods=['GET', 'POST'])
def reset_page(token):
    
    user = User.verify_reset_token(token)

    
    if request.method == 'POST':
        
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
    
        if password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif len(password1) > 15:
            flash('Password must be shorter than 15 characters.', category='error')
        else:
            hashed_password = generate_password_hash(
                    password1, method='scrypt')
            user.password = hashed_password
            db.session.commit()
            login_user(user, remember=True)
            flash('Password updated successfully', category='success')
            return redirect(url_for('main.home'))
            
    if user is None:
        flash('If an account with this email address exists, a password reset message will be sent shortly.', category="sucess")

            
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))    
    
    if user is None:
        flash('Invalid or Expired Token', category='error')
        return redirect(url_for('users.request_page'))
    
    return render_template('reset.html', user=current_user)

website/templates/article.html
{% extends 'index.html' %}

{% block title %}Notify{% endblock %}
{% block content %}
{% for article in articles.values() %}
    {% if article_subject == article['article_subject'] %}
        <div class="row">
            <div class="col d-block justify-content-center text-center mt-3">
                <img class="article-img mb-3"src="{{ url_for('static', filename='imgs/' + article.article_image) }}" class="img-fluid w-50" alt="Article Image">   
                <h1>{{ article['article_title'] }}</h1>
                <p class="fs-5 mt-3">{{ article['article_content'] }}</p>
                <p class=" mt-3 text-muted">Author: {{ article['article_author'] }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}
{% endblock %}

website/templates/foo.html
{% extends 'index.html'%}
{% block title %}Notify{% endblock %}
{% block content %}
<div class="pt-5 mb-5 rounded-5">
    <div class="row">
        <div class="col-md-6 order-md-1 order-2 text-center text-md-start">
            <h1 class="display-3 text-dark fw-bold mb-4">Welcome to Notify!</h1>
            <p class="fw-bold h3 mb-4">Take Notes. Stay Organized. Be Productive.</p>
            <a class="btn btn-primary btn-lg mt-4" href="{{ url_for('users.register') }}" >Register Now</a>
        </div>
        <div class="col-md-6 order-md-1 d-flex justify-content-center align-items-center">
            <img src="static/imgs/relax.png" class="img-fluid w-sm-50 foo-img" alt="Coffee Shop Image">
        </div>
    </div>
</div>
<div class="row align-items-md-stretch">
    <div class="col-md-6 mb-3">
        <div class="h-100 p-5 bg-body-tertiary d-flex flex-column justify-content-center align-items-center border rounded-3">
            <h2 class="lead text-dark mb-3">Increase your creativity</h2>
            <img src="static/imgs/puzzle.png" class="img-fluid w-50 mb-4">
            <a class="btn btn-outline-lg border border-dark" href="{{ url_for('articles.article', article_subject=article[1].article_subject)}}">Know More</a>
        </div>
    </div>
    <div class="col-md-6 mb-3">
        <div class="h-100 p-5 bg-body-tertiary d-flex flex-column justify-content-center align-items-center border rounded-3">
            <h2 class="lead text-dark mb-3">Organize your thoughts</h2>
            <img src="static/imgs/sticky-note.png" class="img-fluid w-50 mb-4">
            <a class="btn btn-outline-lg border border-dark" href="{{ url_for('articles.article', article_subject=article[2].article_subject)}}">Know More</a>
        </div>
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends 'index.html' %}
{% block title %}Notify{% endblock %}
{% block content %}

{% if user.is_authenticated %}
  <div class="nav-scroller bg-body d-flex justify-content-center align-items-center mb-3">
    <nav class="nav" aria-label="Secondary navigation">
      <span class="btn btn-primary rounded-pill me-3" aria-current="page">
        All Notes
        <span class="badge text-bg-light rounded-pill align-text-bottom">{{num_notes}}</span>
      </span>
    </nav>
  </div>
{% endif %}

<div class="content-wrapper">
<div class="row">
  <div class="col">
    <div class="d-flex flex-grow-1 flex-column">
      <div class="d-flex justify-content-start align-items-center lead fs-2"><p id="greet" class="mx-2"></p><p>{{user.username}}!</p></div>
      <small id="time" class="text-muted"></small>
      <hr>
      {% if user.notes %}
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4">
      {% for note in notes.items %}
      <div class="col">
        <div class="card h-100 w-100 py-3 overflow-hidden rounded-4" style="background-color: #ffff88;">
          <div class="card-body d-flex flex-column justify-content-between h-100 p-4 pb-3 text-dark">
            <h5 class="card-title lh-1 fw-bold">{{ note.text[:15]}}...</h5>
            <small>{{ note.date.strftime('%Y-%m-%d') }}</small>
          </div>
          <div class="card-footer bg-transparent border-0">
            <ul class="d-flex list-unstyled justify-content-center mb-0">
              <li class="me-3">
                <img src="{{url_for('static', filename = 'profile_pics/' + note.author.image_file)}}" class="rounded-circle border border-white" width="32" height="32">
              </li>
              <li class="d-flex align-items-center">
                <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{ note.id }}" class="btn-primary btn-sm btn">Open</button>
                <div class="modal fade" id="exampleModal{{ note.id }}" tabindex="-1" role="dialog" aria-labelledby="noteModalLabel{{ note.id }}" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="noteModalLabel{{ note.id }}">Note Text</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        </button>
                      </div>
                      <div class="modal-body">
                        <p>{{ note.text }}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-primary"><a href="{{url_for('notes.note', note_id=note.id)}}" style="text-decoration: none; color: white">Open</a></button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="d-flex align-items-center ms-3">
                <button type="button" data-bs-toggle="modal" data-bs-target="#editModal{{ note.id }}" class="btn-primary btn-sm btn">Edit</button>
                <div class="modal fade" id="editModal{{ note.id }}" tabindex="-1" role="dialog" aria-labelledby="noteModalLabel{{ note.id }}" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="noteModalLabel{{ note.id }}">Note Text</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <form method="post" action="{{url_for('notes.edit_note')}}">
                          <div class="form-group">
                            <textarea name="edit_note" id="edit_note" class="form-control w-100 my-4" placeholder="Reorganize your thoughts" style="height: 100px;">{{note.text}}</textarea>
                          </div>
                          <input type="hidden" name="noteId" value="{{note.id}}">
                          <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="d-flex align-items-center ms-3">
                <button type="button" class="btn-danger btn-sm btn" aria-label="Close" data-bs-toggle="modal" data-bs-target="#deleteModal{{ note.id }}">Delete</button>
                <div class="modal fade" id="deleteModal{{note.id}}" tabindex="-1" role="dialog" aria-labelledby="noteModalLabel{{note.id}}" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="noteModalLabel{{ note.id }}">Delete Note?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <p><span class="fw-bold">Delete the note: </span>{{note.text[:20]}}...</p>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary btn-sm" data-bs-dismiss="modal">Cancel</button>
                          <button type="button" class="btn-danger btn-sm btn" aria-label="Close" onClick="deleteNote({{note.id}})">Delete</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>  
              </li>
            </ul>
          </div>
        </div>
      </div>
        {% endfor %}
      {% else %}
      <h1>No notes here</h1>
      {% endif %}
    </div>

      <!-- Display pagination links -->
      <div class="col">
        <div class="pagination">
          {% if notes.has_prev %}
            <a href="{{ url_for('main.home', page=notes.prev_num) }}" class="page-link">&laquo; Previous</a>
          {% else %}
            <span class="btn btn-outline-info page-link disabled">&laquo; Previous</span>
          {% endif %}
  
          {% for num in notes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if num %}
              {% if notes.page == num %}
                <span class="page-link active">{{ num }}</span>
              {% else %}
                <a href="{{ url_for('main.home', page=num) }}" class="btn btn-outline-info page-link">{{ num }}</a>
              {% endif %}
            {% else %}
              <span class="btn btn-outline-info page-link">...</span>
            {% endif %}
          {% endfor %}
  
          {% if notes.has_next %}
            <a href="{{ url_for('main.home', page=notes.next_num) }}" class="btn btn-outline-info page-link">Next &raquo;</a>
          {% else %}
            <span class="btn btn-outline-info page-link disabled">Next &raquo;</span>
          {% endif %}
        </div>
      <div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}Notify{% endblock %}</title>
    <link rel="icon" type="image/png" href="{{url_for('static', filename='imgs/favicon.png')}}">
</head>
<body>
  <nav class="navbar navbar-expand-lg" aria-label="Offcanvas navbar large">
    <div class="container">
      <a class="navbar-brand" href="{{url_for('main.home')}}"><img style="width: 80px; height: 80px" src="{{url_for('static', filename='imgs/Notify-logo.png')}}" alt="Notify"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
        <div class="offcanvas-header">
          <img style="width: 80px; height: 80px" src="static/imgs/Notify-logo.png" alt="Notify">
          <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" id="home" href="{{url_for('main.home')}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile" href="{{url_for('users.profile')}}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="logout" href="{{url_for('users.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" id="login" href="{{url_for('users.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="register" href="{{url_for('users.register')}}">Register</a>
            </li>
          </ul>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>
  <section id="alerts">
    <div class="container">
      <div class="row my-3">
        <div class="col">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                {% if category == 'error' %}
                  <div class="toast-container position-fixed top-0 start-50 translate-middle-x p-3 text-dark">
                    <div id="liveToast" class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
                      <div class="toast-header text-bg-danger text-white">
                        <i class="bi bi-exclamation-circle-fill me-3"></i>
                        <strong class="me-auto">Notify</strong>
                        <small>Just now</small>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
                      </div>
                      <div class="toast-body text-secondary-emphasis">
                        {{message}}
                      </div>
                    </div>
                  </div>
                {% else %}
                <div class="toast-container position-fixed top-0 start-50 translate-middle-x p-3 text-dark">
                  <div id="liveToast" class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header text-bg-primary text-white">
                      <i class="bi bi-exclamation-circle-fill me-3"></i>
                      <strong class="me-auto">Notify</strong>
                      <small>Just now</small>
                      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                    <div class="toast-body text-secondary-emphasis">
                      {{message}}
                    </div>
                  </div>
                </div>
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </section>

  <section class="container">
        <!-- Main Content -->
            {% block content %}{% endblock %}

{% if user.is_authenticated %}
<div class="sidebar-wrapper">
<div class="d-flex flex-shrink-0 align-items-center justify-content-center" style="height: 4.5rem;">
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center justify-content-center p-3 link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="{{img_file}}" alt="Profile" class="rounded-circle" width="48" height="48">
    </a>
    <ul class="dropdown-menu text-small shadow">
      <li><a type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addNoteModal">New note...</a></li>
      <li><a class="dropdown-item" href="{{url_for('users.profile')}}">Profile</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Log out</a></li>
    </ul>
  </div>
</div>
</div>
  <!-- Publish Note Modal -->
  <div class="modal fade" id="addNoteModal" tabindex="-1" role="dialog" aria-labelledby="addNoteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="noteModalLabel">Add Note</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post" action="/home">
            <div class="form-group">
              <textarea name="note" id="note" class="form-control w-100 my-4" placeholder="Organize your thoughts" style="height: 100px;"></textarea>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-lg text-nowrap w-100 mb-3">Add Note<i class="bi bi-sticky-fill mx-2"></i></button>
            </div>            
          </form>
        </div>
      </div>
    </div>
  </div>
{% endif %}
</section>

{% if user.is_authenticated == False %}
<section class="container">
  <footer class="pt-3 mt-4 mb-4 text-body-secondary border-top d-flex justify-content-between">
    <p class="footer-year">© 2023</p>
    <p class="display-7 footer-credit">a project by <a href="https://github.com/devpedrofurquim" target="_blank" class="pedro-furquim fw-bold">pedro furquim</a></p>
  </footer>
</section>
{% endif %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/38.1.0/classic/ckeditor.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

website/templates/login.html
{% extends 'index.html'%}
{% block title %}Notify{% endblock %}
{% block content %}
  <div class="row align-items-center g-lg-5">
    <div class="col-lg-7 text-center">
      <div class="d-flex justify-content-center align-items-center">
        <img src="static/imgs/coffee-shop.png" alt="" class="w-50">
      </div>
      <h1 class="display-6 fw-bold lh-1 text-body-emphasis mb-3">Welcome to Notify</h1>
      <p class="col-lg-12 fs-5 text-center text-body-secondary">Take Notes. Stay Organized. Be Productive.</p>
    </div>
    <div class="col-md-10 mx-auto col-lg-5">
      <form class="p-4 p-md-5 border rounded-3 bg-body-tertiary" method="post">
        <div class="form-floating mb-3">
          <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" aria-describedby="userEMail">
          <label for="email">Email address</label>
        </div>
        <div class="form-floating mb-3">
          <input type="password" autocomplete="off" name="password" class="form-control" id="password" placeholder="Password">
          <label for="password">Password</label>
        </div>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" name="remember-me" value="remember-me"> Remember me</input>
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
        <hr class="my-4">
        <div>
          <small class="text-muted">
              <a class="ml-2 text-decoration-none" href="{{ url_for('users.request_page') }}">Forgot Password?<a/>
          </small>
      </div>
      </form>
    </div>
  </div>
{% endblock %}

website/templates/note.html
{% extends 'index.html' %}
{% block title %}Notify{% endblock %}
{% block content %}
<article class="note-container">
    <div class="note-header">
        <div>
            <img class="rounded-circle note-img" src="{{url_for('static', filename = 'profile_pics/' + note.author.image_file)}}">
            <h3>{{note.author.username}}</h3>
        </div>
        <small class="text-muted">{{note.date.strftime('%Y-%m-%d')}}</small>
    </div>
    <div class="note-body">
        <p>{{ note.text }}</p>
    </div>
</article>
{% endblock content%}